/*
parenthetical possibilities
Write a function, parentheticalPossibilities, that takes in a string as an argument. 
The function should return an array containing all of the strings that could be generated by expanding all parentheses of the string into its possibilities.
For example, the possibilities for 'x(mn)yz' are 'xmyz', 'xnyz'.
*/

const parentheticalPossibilities = (s, str = s.split(",")) => {
  // console.log(str)

  if (s === "" || !s.match(/\(\w+\)/) || str.every((str) => !str.match(/\(\w+\)/))) return str

  const simplifiedStrings = str.reduce((acc, val) => {
    let possibilities = []
    const simpleStr = val.replace(/\(([a-zA-Z]+)\)/, (_, strCatched) => {
      // console.log(strCatched)
      possibilities = strCatched.split("")
      return "-"
    })

    const newStrings = possibilities.map((letter) => {
      return simpleStr.replace(/-/, letter)
    })

    // console.log(simpleStr, newStrings)

    return [...acc, ...newStrings]
  }, [])

  // console.log(simplifiedStrings)

  return parentheticalPossibilities(s, simplifiedStrings)
}

console.log(parentheticalPossibilities("x(mn)yz")) // -> [ 'xmyz', 'xnyz' ]
console.log(parentheticalPossibilities("(qr)ab(stu)c")) // -> [ 'qabsc', 'qabtc', 'qabuc', 'rabsc', 'rabtc', 'rabuc' ]
console.log(parentheticalPossibilities("taco")) // -> ['taco']
console.log(parentheticalPossibilities("")) // -> ['']
console.log(parentheticalPossibilities("(etc)(blvd)(cat)")) // ->
// [
//  'ebc', 'eba', 'ebt', 'elc', 'ela',
//  'elt', 'evc', 'eva', 'evt', 'edc',
//  'eda', 'edt', 'tbc', 'tba', 'tbt',
//  'tlc', 'tla', 'tlt', 'tvc', 'tva',
//  'tvt', 'tdc', 'tda', 'tdt', 'cbc',
//  'cba', 'cbt', 'clc', 'cla', 'clt',
//  'cvc', 'cva', 'cvt', 'cdc', 'cda',
//  'cdt'
// ]

/*
const parentheticalPossibilities = (s) => {
  if (s === "") return [""]

  const { remaining, chars } = getOptions(s)
  const suffixes = parentheticalPossibilities(remaining)
  const possibilities = []

  for (let char of chars) {
    for (let suffix of suffixes) {
      possibilities.push(char + suffix)
    }
  }

  return possibilities
}

const getOptions = (s) => {
  if (s[0] === "(") {
    const endIdx = s.indexOf(")")
    const remaining = s.slice(endIdx + 1)
    const chars = s.slice(1, endIdx).split("")
    return { remaining, chars }
  } else {
    const remaining = s.slice(1)
    const chars = [s[0]]
    return { remaining, chars }
  }
}
*/
